# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b94d23b76a48d470604c9275af9d4892240af9af37c965759a112f57a4f434a7d3deb5b6e760cc145e0542340d06d550e4f47d27925bf7f4afdf4032fc5124d7

test:
  secret_key_base: d259c424d7766fa7214cb4ce7f39c26e111d097af59dc2560e8c5d3021b834c20d564edcd5e9cdd73b4f3dedf96970b9c2a272f7ac6e117707537d2571ef626a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
